spring.application.name=learn

# configure server port
server.port=8181

# configure customer property
my.name=Ashvin Parmar


# include all endpoints - Do not use this
# management.endpoints.web.exposure.include=*  
# exclude endpoints
# management.endpoints.web.exposure.exclude=env,beans 

  
# include only specific endpoints
management.endpoints.web.exposure.include=health,info 
# enable info environment variable access
management.info.env.enabled=true

# provide information envs
info.app.name=Learning SpringBoot
info.app.description=A SpringBoot learning repository
info.app.version=1.0.0
info.app.custom.name=customer name


# implementing security
# Show full details only to authorized/authenticated users, not the public
management.endpoint.health.show-details=when-authorized
management.endpoint.health.show-components=when-authorized

management.endpoint.env.enabled=false
management.endpoint.shutdown.enabled=false

