spring.application.name=msgboard

# Thymeleaf to read directly from your actual project source folder
spring.thymeleaf.prefix=file:src/main/resources/templates/

spring.thymeleaf.cache=false    
# for production - use old loaded version page for speed, but for developer environment - do not use old version, show a clean latest version of page or html(client-side technology)

